language: node_js
node_js:
  - "5"
  - "6"
before_install:
  - echo "Updating npm, because of the following problem - https://github.com/npm/npm/issues/11088"
  - npm update -g
  - npm --version
before_script:
  - npm ls --depth=0
  - npm run build
  - npm run build-prod-all
script:
  - npm test
