language: node_js
node_js:
  - "5"
  - "6"
before_install:
  - echo "Updating npm, because of the following problem - https://github.com/npm/npm/issues/11088"
  - npm update -g
  - npm --version
before_script:
  - npm ls --depth=0 2> /dev/null; if [ $? -eq 0 ]; then echo "No peerDependency errors"; else echo "peerDependency errors detected - see message bellow"; fi;
  - echo "There might be some peerDependency errors about Victory, it doesn't affect the project though. An issue is opened at https://github.com/FormidableLabs/victory/issues/275"
  - npm run build
  - npm run build-prod-all
script:
  - npm test
