language: node_js
node_js:
  - "5"
  - "6"
before_script:
  - npm ls --depth=0; if [ $? -eq 0 ]; then echo "No peerDependency errors"; false; else echo "peerDependency errors detected - see message bellow"; false; fi;
  - echo "There might be some peerDependency errors about Victory, it doesn't affect the project though. An issue is opened at https://github.com/FormidableLabs/victory/issues/275"
  - npm run build
  - npm run build-prod-all
script:
  - npm test
