language: node_js
node_js:
  - "4"
  - "5"
before_script:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "5" ]; then npm install invariant; fi'
  - npm run build
  - npm run build-prod-all
script:
  - npm test
